url: https://isthmuscohousing.org
baseurl: /

# Site settings
title: Isthmus Cohousing
email: isthmuscohousing@gmail.com
description: "A website for our cohousing site"


# Team names, titles and social links
people:
- name: Claire Stedden
  pic: 1
  position: co-founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/clairestedden/

- name: Will Ochowicz
  pic: 2
  position: co-founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/william-ochowicz-515907b0/

- name: Melinda Morang
  pic: 4
  position: co-founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/melinda-morang-915a1b35/

- name: Ian Shay
  pic: 5
  position: co-founder
  social:

- name: Willie Stedden
  pic: 3
  position: co-founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/willstedden/

- name: Victoria Steinberg
  position: co-founder

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/people/Isthmus-Cohousing/61558377656371/
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: instagram
    url: http://instagram.com/isthmuscohousing
  - title: envelope
    url: mailto:isthmuscohousing@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: Madison, WI

# Build settings
markdown: kramdown
permalink: pretty
